export const flightLocations = [
  { city: "Dhaka", country: "Bangladesh" },
  { city: "New York", country: "United States" },
  { city: "London", country: "United Kingdom" },
  { city: "Delhi", country: "India" },
  { city: "Dubai", country: "United Arab Emirates" },
  { city: "Istanbul", country: "Turkey" },
  { city: "Doha", country: "Qatar" },
  { city: "Jeddah", country: "Saudi Arabia" },
  { city: "Singapore", country: "Singapore" },
  { city: "Bangkok", country: "Thailand" },
  { city: "Tokyo", country: "Japan" },
  { city: "San Francisco", country: "United States" },
  { city: "Toronto", country: "Canada" },
  { city: "Frankfurt", country: "Germany" },
  { city: "Kuala Lumpur", country: "Malaysia" },
  { city: "Los Angeles", country: "United States" },
  { city: "Sydney", country: "Australia" },
];
